### ISSUE TITLE
[EOEPCA/IAM] Update Keycloak major version, 24 to 26

### ISSUE THREAD

**Issue by w-jfe** [EOEPCA/iam#35]
Keycloak should be updated to the most recent version (probably 26).

After updating Keycloak, it should be verified if the port-9443-redirect workaround in the Keycloak route is still required. If it is obsolete, it should be removed.

**Comment by w-scho** [comment]
Observations with Keycloak 26.1.3 on internal test environment:

* There are sporadic 500 and 503 errors when accessing services. However, this may be related to deficiencies of the environment
* Keycloak logs are flooded by `Non-secure context detected; cookies are not secured, and will not be available in cross-origin POST requests` warnings. It seems that the warnings are caused by the Crossplace Keycloak Provider, which ist currently configured to access Keycloak via HTTP.
* User sessions seem to survive a Keycloak restart (as documented)

**Comment by w-scho** [comment]
A database that has been migrated to Keycloak 26 ist not fully compatible with Keycloak 24 any more. One (the main?) reason for this is that Keycloak 25/26 uses the Argon2 password hashing algorithm instead of PBKDF2. Keycloak seems to rehash passwords if it gets the chance to do so (e.g., when a user logs in?). At least some passwords that had not been changed after the update used the new algorithm, which prevented logging in as the affected users after a downgrade to Keycloak 24. Keycloak startup, however, worked without any noticeable problems.
In any case, backing up the database before upgrading to Keycloak 26 seems to be a good idea.

**Comment by w-scho** [comment]
Keycloak on the reference environment has been updated and mostly seems to be working as expected.
This morning (2025-03-21) until 10:16, however there were lots of error messages saying "java.lang.RuntimeException: Client does not have a service account."
It is not yet clear what caused these errors and why they did not occur any more after 10:16am. Maybe this was caused by updates of some client via the Crossplane Keycloak Provider due to a similar reason as described here: https://github.com/keycloak/keycloak/discussions/21848 and https://github.com/keycloak/keycloak/issues/32530

**Comment by w-scho** [comment]
The following errors occurred repeatedly last night (2025-03-26):

```
org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection [Acquisition timeout while waiting for new connection] [n/a]
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:63)
```

```
 java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because the return value of "java.sql.SQLException.getSQLState()" is null
        at org.keycloak.connections.jpa.PersistenceExceptionConverter.lambda$convert$1(PersistenceExceptionConverter.java:97)
```
There are no corresponding messages in the PostgreSQL log file.
The cause is still unknown. The errors may or may not be related to the Keycloak update.
